version: '3'

services:
  backend:
    build:
      context: ./django
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./django:/django
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql://$DB_USER:$DB_PASSWORD@db:3306/$MYSQL_DB_NAME
    env_file: .env

  frontend:
    build:
      context: ./reactapp
    ports:
      - "3000:3000" 
    volumes:
      - ./reactapp:/reactapp  
    command: sh -c "npm install && npm start"
    environment:
      - CHOKIDAR_USEPOLLING=true

  nginx:
    image: nginx:1.25.2
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf
      - ./django/static:/var/www/django/static
    # Uncomment react_build during production.
      # - react_build:/var/www/reactapp 

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"  
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  react_build:
  mysql_data:
